### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by imSp4rky** [namreeb/wowreeb#13]
When loading the application with an invalid config.xml there's no error message or anything.

Was able to duplicate these steps on another machine, If you have a <Realm> and don't close it correctly such as not having </Realm> or a miss spelling such as </Relm>double clicking the shortcut just spins for a second and nothing pops up.

Suggestion to just add a feedback "Incorrect config file" or display feedback on where it's expecting a closing

**Comment by namreeb** [comment]
Fixed in [3.2](https://github.com/namreeb/wowreeb/releases/tag/3.2).
