### ISSUE TITLE
not working in Windows 7

### ISSUE THREAD

**Issue by laytya** [namreeb/wowreeb#19]
Wowreeb cant start wow.exe -  there is no api-ms-win-core-version-l1-1-1.dll

![Error](https://user-images.githubusercontent.com/20452393/187059827-db63ea72-f134-4677-a620-53ae653da118.png)

**Comment by laytya** [comment]
Found all 3 missed DLL in Windows 7 - now its starts
edit: link removed for security
Need to put it to C:\Windows\SysWOW64

**Comment by namreeb** [comment]
Windows 7 has been EOL for three years now.  Sorry, not going to fix this.
