### ISSUE TITLE
DLL loading improvements

### ISSUE THREAD

**Issue by hannesmann** [namreeb/wowreeb#20]
**1. Make the `Method` field optional:**

If the DLL injects code by relying on `DLL_PROCESS_ATTACH` and `DLL_PROCESS_DETACH` instead of exporting a load method, it can't be used by wowreeb. 

**2. Allow loading multiple DLLs on a single realm:**

The main use case here is for people who want to use nampower and my project, [VanillaFixes](https://github.com/hannesmann/vanillafixes), at the same time. 

Related issue: https://github.com/hannesmann/vanillafixes/issues/3

**Comment by namreeb** [comment]
Good suggestions.  Should be fixed in [3.5](https://github.com/namreeb/wowreeb/releases/tag/3.5).
