### ISSUE TITLE
Default FOV if value is missing

### ISSUE THREAD

**Issue by joao-fidalgo** [namreeb/wowreeb#4]
Wowreeb shouldn't change the field of view if a value isn't set on config.xml

**Comment by namreeb** [comment]
Is it doing so?  It seems like the default value is 0, and it won't be set if the value is <= 0.1

**Comment by joao-fidalgo** [comment]
I removed the FoV node, and it was setting a custom FoV anyways.

**Comment by namreeb** [comment]
I'm not able to reproduce this.  Note that if you update the config, you have to restart the systray app.  Maybe I should add a background thread to monitor the file for changes and load them.  Can you confirm if restarting the launcher solves your issue?

**Comment by joao-fidalgo** [comment]
You're right. I might botched it up by changing config.xml and not restarting wowreeb.exe.

Anyways i feel like the default FoV on config.xml shouldn't be that high, and should be set to the default value, 1.570796371 according to OwnedCore.

**Comment by namreeb** [comment]
There is no default value.
