### ISSUE TITLE
Clear Cache/WDB

### ISSUE THREAD

**Issue by FLeXyo** [namreeb/wowreeb#5]
Would it be a reasonable idea to clear Cache/WDB if the realmlist differs from the previous run of a client?

**Comment by namreeb** [comment]
To do that 100% of the time would involve saving the realmlist of the previous run to the disk or registry somewhere, which I would prefer to avoid.  I could maybe add an option to the configuration xml and have it just remember the last realmlist used in the launcher's memory.

**Comment by FLeXyo** [comment]
Yeah that sounds fine to me.

I used to clear the cache on every launch in my own launcher, but I'm not as sure of the consequences as you might be.

**Comment by namreeb** [comment]
I just released 2.0 which adds an option for this.  I made it even simpler, where when the option is enabled, the cache is emptied before each launch of wow.
