### ISSUE TITLE
Program closing instantly after launching.

### ISSUE THREAD

**Issue by CrimsonHollow** [namreeb/wowreeb#6]
This issue pops up after the 2.0 update. Not sure if its my issue or not. Been trying to find solutions for a month since 2.1 dropped. Any ideas?

**Comment by namreeb** [comment]
Can you provide a bit more information?  Are you saying that the launcher closes right after running the launcher?  The launcher closes right after launching wow?  Wow closes right after being launched?  Are you using the 32 or 64 bit version of the launcher?  Does it happen every time, or is it intermittent?

**Comment by CrimsonHollow** [comment]
The launcher closes right after at the launch of the program itself. it wont show in the tray. And in the proccess window i can see it starting and closing right after. It happens both on 32 and 64 bit and for every release except the first one. Also it happened to a friend of mine all the time just so i can be sure its not from my end.

**Comment by namreeb** [comment]
Can you post your config file here?

**Comment by CrimsonHollow** [comment]
I didnt do any changes to it. its just as it was given! Could that be the issue?

**Comment by CrimsonHollow** [comment]
Hmm after some more tweaking with the config file it feels like it wont close no more. But i just get dll errors like Could not get instance of ICLRuntimeInfo and CLRLoad failed.

**Comment by namreeb** [comment]
I feel like you're trying to tell it to load a CLR DLL when you shouldn't be.  Try dropping the `<CLR>` tag.

**Comment by CrimsonHollow** [comment]
Hmm okays. That seems to work! I guess we are done. Thanks a bunch and sorry for any inconveniences!

**Comment by namreeb** [comment]
No problem.  I will plan to take a look at the user feedback code and see if I can't make some more meaningful error messages than just silently exiting :)

**Comment by namreeb** [comment]
Without a reproduction guide, I do not see how to trigger this behavior.  Closing for now.  If someone comes up with a configuration file that causes the launcher to merely exit with no feedback whatsoever, please feel free to post here.
